# Generated by Django 4.2.11 on 2025-05-17 00:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rh.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
                ('nacionalidade', models.CharField(default='Brasileira', max_length=100)),
                ('naturalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('data_admissao_primeiro_vinculo', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('afastado', 'Afastado')], default='ativo', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador_perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_referencia', models.DateField()),
                ('data_pagamento', models.DateField()),
                ('salario_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_descontos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario_liquido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VinculoEmpregaticio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ'), ('estagio', 'Estágio'), ('outro', 'Outro')], max_length=50)),
                ('cargo', models.CharField(max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carga_horaria_semanal', models.IntegerField(blank=True, null=True)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='rh.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramacaoFerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_aquisitivo_inicio', models.DateField()),
                ('periodo_aquisitivo_fim', models.DateField()),
                ('data_inicio_gozo', models.DateField()),
                ('data_fim_gozo', models.DateField()),
                ('dias_gozados', models.IntegerField()),
                ('status', models.CharField(choices=[('programada', 'Programada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programacao_ferias', to='rh.vinculoempregaticio')),
            ],
        ),
        migrations.CreateModel(
            name='PrazoTrabalhista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prazo', models.CharField(choices=[('experiencia_45', 'Término Contrato Experiência 45 dias'), ('experiencia_90', 'Término Contrato Experiência 90 dias'), ('aviso_previo', 'Término Aviso Prévio'), ('desligamento', 'Data de Desligamento'), ('outro', 'Outro')], max_length=50)),
                ('data_prazo', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cumprido', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prazos', to='rh.vinculoempregaticio')),
            ],
        ),
        migrations.CreateModel(
            name='ObrigacaoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_obrigacao', models.CharField(choices=[('fgts', 'FGTS'), ('inss', 'INSS'), ('irrf', 'IRRF'), ('rais', 'RAIS'), ('e_social', 'eSocial'), ('outro', 'Outro')], max_length=50)),
                ('periodo_referencia', models.DateField()),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cumprida', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obrigacoes_legais', to='rh.vinculoempregaticio')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFolhaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('provento', 'Provento'), ('desconto', 'Desconto')], max_length=20)),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('historico_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='rh.historicopagamento')),
            ],
        ),
        migrations.AddField(
            model_name='historicopagamento',
            name='vinculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_pagamentos', to='rh.vinculoempregaticio'),
        ),
        migrations.CreateModel(
            name='DocumentoDigitalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('ctps', 'CTPS'), ('rg', 'RG'), ('cpf', 'CPF'), ('comprovante_residencia', 'Comprovante de Residência'), ('certificado_escolaridade', 'Certificado de Escolaridade'), ('exame_admissional', 'Exame Admissional'), ('contrato_trabalho', 'Contrato de Trabalho'), ('ficha_registro', 'Ficha de Registro'), ('outro', 'Outro')], max_length=100)),
                ('arquivo', models.FileField(upload_to=rh.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='rh.colaborador')),
                ('vinculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='rh.vinculoempregaticio')),
            ],
        ),
        migrations.CreateModel(
            name='BancoDeHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo_lancamento', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito')], max_length=10)),
                ('horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banco_horas', to='rh.vinculoempregaticio')),
            ],
        ),
        migrations.CreateModel(
            name='AtestadoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField()),
                ('data_inicio_afastamento', models.DateField()),
                ('data_fim_afastamento', models.DateField()),
                ('cid', models.CharField(blank=True, max_length=10, null=True)),
                ('medico_nome', models.CharField(blank=True, max_length=100, null=True)),
                ('medico_crm', models.CharField(blank=True, max_length=20, null=True)),
                ('documento_atestado', models.FileField(blank=True, null=True, upload_to=rh.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atestados_medicos', to='rh.vinculoempregaticio')),
            ],
        ),
    ]
