# Generated by Django 4.2.11 on 2025-05-17 00:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Implemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('unidade_medida', models.CharField(choices=[('diesel', 'Diesel'), ('gasolina', 'Gasolina'), ('etanol', 'Etanol'), ('litro', 'Litro')], default='diesel', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('ano_fabricacao', models.IntegerField()),
                ('chassi', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('tipo_veiculo', models.CharField(choices=[('carro', 'Carro'), ('caminhao', 'Caminhão'), ('trator', 'Trator'), ('moto', 'Moto'), ('outro', 'Outro')], default='carro', max_length=50)),
                ('capacidade_tanque', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quilometragem_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ativo', models.BooleanField(default=True)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('tipo_combustivel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos', to='veiculos.tipocombustivel')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_servico', models.DateField()),
                ('quilometragem_servico', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('descricao_servico', models.TextField()),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('oficina', models.CharField(blank=True, max_length=100, null=True)),
                ('proxima_manutencao_data', models.DateField(blank=True, null=True)),
                ('proxima_manutencao_quilometragem', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo_manutencao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veiculos.tipomanutencao')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='veiculos.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('quantidade_litros', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('valor_por_litro', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quilometragem_atual', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('posto_combustivel', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo_combustivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veiculos.tipocombustivel')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to='veiculos.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='VeiculoImplemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conexao', models.DateField()),
                ('data_desconexao', models.DateField(blank=True, null=True)),
                ('implemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_veiculos', to='veiculos.implemento')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_implementos', to='veiculos.veiculo')),
            ],
            options={
                'unique_together': {('veiculo', 'implemento', 'data_conexao')},
            },
        ),
    ]
